# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build with Node.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Zip artifact for deployment
      if: github.event_name == 'push'
      run: zip dist.zip ./dist/* -r

    - name: Archive production artifacts
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: 'dist-${{ runner.os }}-${{ runner.arch }}-${{ matrix.node-version }}'
        path: dist.zip

    - name: Generate artifact attestation
      if: github.event_name == 'push'
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: 'dist.zip'

